name: build
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: [self-hosted, private, linux, x64]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Fetch release version
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git pull

          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo "version = '$checkov_version'" > 'bridgecrew/version.py'
          echo "version = '$checkov_version'"
          new_tag=$checkov_version
          echo "bc-python-hcl2>=0.3.5" > 'kubernetes/requirements.txt'
          echo "bridgecrew==$new_tag" >> 'kubernetes/requirements.txt'
          pipenv update
          git commit -m "New release version '$checkov_version'" bridgecrew/version.py kubernetes/requirements.txt Pipfile.lock || echo "No changes to commit"
          git push origin
          git tag -f $new_tag
          git push origin $new_tag
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: sleep and wait for package to refresh
        run: |
          sleep 2m
  publish-bridgecrew-dockerhub:
    runs-on: [self-hosted, private, linux, x64]
    needs: bump-version
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: |
          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo ::set-env name=RELEASE_VERSION::$(echo $checkov_version)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bridgecrew/bridgecrew
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  publish-bridgecrew-k8s-dockerhub:
    runs-on: [self-hosted, private, linux, x64]
    needs: bump-version
    steps:
      - uses: actions/checkout@master
      - name: update bridgecrew-k8s version
        run: |
          bridgecrew_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo ::set-env name=RELEASE_VERSION::$(echo $bridgecrew_version)
          echo $RELEASE_VERSION
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bridgecrew/bridgecrew-k8s
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          dockerfile: kubernetes/Dockerfile
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
  update-bridgecrew-py-projects:
    needs: publish-bridgecrew-dockerhub
    runs-on: [self-hosted, private, linux, x64]
    steps:
      - uses: actions/checkout@master
      - name: update bridgecrew release
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/bridgecrewio/bridgecrew-action/dispatches --data '{"event_type": "build"}'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
