name: build
on: repository_dispatch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch release version
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git pull

          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo "version = '$checkov_version'" > 'bridgecrew/version.py'
          echo "version = '$checkov_version'"
          new_tag=$checkov_version
          echo "bridgecrew==$new_tag" > 'kubernetes/requirements.txt'

          git commit -m "New release version '$checkov_version'" bridgecrew/version.py kubernetes/requirements.txt || echo "No changes to commit"
          git tag $new_tag
          git push origin $new_tag
  publish-package:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: sleep and wait for package to refresh
        run: |
          sleep 2m
  publish-bridgecrew-dockerhub:
    runs-on: ubuntu-latest
    needs: publish-package
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: |
          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/bridgecrew-py/tags | jq -r '.[0]["name"]' )
          echo ::set-env name=RELEASE_VERSION::$(echo $checkov_version)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bridgecrew/bridgecrew
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
  publish-bridgecrew-k8s-dockerhub:
    runs-on: ubuntu-latest
    needs: publish-package
    steps:
      - uses: actions/checkout@master
      - name: update bridgecrew-k8s version
        run: |
          bridgecrew_version=$(curl -sL https://api.github.com/repos/bridgecrewio/bridgecrew-py/tags | jq -r '.[0]["name"]' )
          echo ::set-env name=RELEASE_VERSION::$(echo $bridgecrew_version)
          echo $RELEASE_VERSION
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bridgecrew/bridgecrew-k8s
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          dockerfile: kubernetes/Dockerfile